Controllers/ReportsController.cs
using BookStore.Models;
using BookStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class ReportsController : Controller
    {
        BookStoreEntities storeDB = new BookStoreEntities();

        //
        // GET: /Reports/

        public ActionResult Index()
        {
            /*var orderDetailViewModel = storeDB.OrderDetails.
                Where(r => r.Order.UserName == User.Identity.Name);*/

            var orders = from u in storeDB.Orders
                         where u.UserName == User.Identity.Name
                         select new OrderDetailViewModel
                         {
                             OrderId = u.Id,
                             TotalOrder = u.Total
                         };

            List<OrderDetailViewModel> orderDetailViewModel = orders.ToList();

            foreach (var item in orderDetailViewModel)
            {
                var ordersDetail = from u in storeDB.OrderDetails
                                   where u.OrderId == item.OrderId
                                   select u;

                item.orderDetail = ordersDetail.ToList();

            }

            foreach (var item in orderDetailViewModel)
            {
                foreach (var itemOrder in item.orderDetail)
                {
                    var ordersBooks = (from u in storeDB.Books
                                      where u.Id == itemOrder.BookId
                                      select u).SingleOrDefault();

                    itemOrder.Book = ordersBooks;

                }
            }


            return View(orderDetailViewModel);
        }

    }
}

Controllers/ShoppingCartController.cs
using BookStore.Models;
using BookStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        BookStoreEntities storeDB = new BookStoreEntities();

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }


        //
        // GET: /Store/AddToCart/5

        public ActionResult AddToCart(int id, int? page)
        {

            // Retrieve the album from the database
            var addedBook = storeDB.Books
                .Single(album => album.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedBook);

            int pageReturn = 1;

            if (page.HasValue)
                pageReturn = page.Value;


            // Go back to the main store page for more shopping
            return RedirectToAction("Details", "Store", new { id = id, page = pageReturn});
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string bookName = storeDB.Carts
                .Single(item => item.Id == id).Book.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(bookName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }

    }
}

Views/Shared/_Layout.cshtml
@using BookStore.App_Code;
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Book Store</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div>
                <div class="float-left">
                    <a href="@Url.Action("Index","Home")"><img alt="The Book Store" src="~/Images/bookmountain.jpg" />
                    <p class="site-title">The Book Store</p>
                    </a>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
                            <li>@Html.AuthorizedActionLink("Book List", "ListBook", "Parameter")</li>
                            <li>@Html.AuthorizedActionLink("Orders", "Index", "Reports")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div>
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Jaime Valencia</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>